### ISSUE TITLE
2015-07-30 Meetup

### ISSUE THREAD

**Issue by spikeheap** [oxrug/oxrug.org#7]
http://www.meetup.com/Oxford-Ruby-Users-Group-OxRUG/events/224127887/

### Date
Thursday 30th July, 7:30pm

### Location 
White October, The Gallery, 54 Marston Street, Oxford OX4 1LF

### Speakers
* Richard Patching (@patchfx) – Hexagonal Coffee (TBA)
* TBA

### To do

- [x] Organise the venue (thanks @benfoxall)
- [x] Organise sponsor for drinks (~£30)
- [x] Confirm speakers
- [x] Create Meetup event
- [x] Announce event on Meetup
- [x] Announce the event on the mailing list
- [x] Announce the event on Twitter
- [x] Sort out video recording/broadcasting for the event

**Comment by spikeheap** [comment]
Haybrook IT have very kindly offered to sponsor £30 to cover drinks and crisps for the evening. Thanks!

**Comment by amn** [comment]
Dear Ryan, I've got one word for you:

UNSUBSCRIBE!

:-D

Cheers.

P.S. How does one control whether one gets notified through these kind of
emails? I don't think this anything to do with me, does it?

**Comment by amnn** [comment]
I'm in the US on the 30th July, sorry! But am happy to push the talk to term time (October).

**Comment by spikeheap** [comment]
Hi @amn, sorry I typo'd and mentioned you by mistake. You're right you're probably not interested in Ruby events in Oxford, UK ;). 

I've edited out your mention, but now you've commented you'll get notifications every time there's a comment – you can change that by clicking the 'Unsubscribe' button on this issue's page. Sorry for the faff!

**Comment by spikeheap** [comment]
Ahh @amnn, that's cool. We'll definitely take your talk in October! Have a good time in the states.

**Comment by spikeheap** [comment]
Unfortunately Richard couldn't make this event either, so we'll have a pub meet instead and schedule talks for August's event.

**Comment by spikeheap** [comment]
This event happened. Thanks to Sarah and Haybrook for sponsoring a couple of rounds of drinks, and thanks to everyone who came!
